# Generated by Django 3.1.2 on 2020-10-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(upload_to='bloging_images/')),
                ('post_text', models.CharField(max_length=1000)),
                ('post_title', models.CharField(max_length=50)),
                ('post_date', models.DateTimeField()),
            ],
        ),
    ]
