# Generated by Django 3.1.2 on 2020-10-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloging',
            name='post_text',
            field=models.TextField(),
        ),
    ]
